<h1 style='color: green;'><center>Multi-dimensional Arrays</center></h1>

Multi-dimensional arrays are fundamental data structures in programming that extend the concept of one-dimensional arrays to multiple dimensions. A multi-dimensional array is an array of arrays where each element is accessed by a sequence of indices.

Dimensions: The number of dimensions determines the rank of the array. For example:

- 1D array: A list of elements accessed by a single index.
- 2D array: An array of arrays, accessed by two indices (rows and columns).
- 3D array: An array of 2D arrays, accessed by three indices (depth, row, and column).
And so forth for higher dimensions.

<img src="multi-dimensional.png" alt="Example Image" >

Indexing: Elements in a multi-dimensional array are accessed using multiple indices corresponding to each dimension. For example, in a 2D array, array[row_index][column_index] accesses a specific element.

Initialization: Multi-dimensional arrays can be initialized during declaration or dynamically allocated depending on the programming language.

<h4 style='color: green;'>Declaration and Initialization in Python Programming</h4>
<p><em>The syntax for declaring a one-dimensional array varies depending on the programming language. <br>
Here are example in Python.</em></p>

In [6]:
## Importing numpy for creating array, numpy provides many function and methods for manipulating arrays.

import numpy as np 

array_obj_2D=[[1,2,3], [4,5,6], [7,8,9]]
Array_2D=np.array(array_obj_2D)

array_obj_3D=[[[1,2,3], [4,5,6], [7,8,9]]]
Array_3D=np.array(array_obj_3D)

## Printing the 2D array and its dimensional
## In numpy we can check the dimension of any array using ndim function.

print("Array Dimension:- ",Array_2D.ndim)  
print(Array_2D)
print('\n')

print("Array Dimension:- ",Array_3D.ndim)  
print(Array_3D)

Array Dimension:-  2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Dimension:-  3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


<p><em>In this way you can create 'n' dimensional arrays.</em></p>

<h3 style='color: green;'>Applications:</h3>

- Image Processing: Pixel values in images are often stored in 2D arrays (for grayscale) or 3D arrays (for RGB color images).
- Matrices: Used extensively in mathematics for representing matrices and performing matrix operations.
- Simulation and Modeling: Used in simulations where data needs to be organized in multiple dimensions (e.g., spatial dimensions in physics simulations).